import type { CharacterSheet } from "./types";

export const EMPTY_CHARACTER: CharacterSheet = {
  name: "",
  chronicle: "",
  description: "",
  player: "",
  sire: "",
  clan: "",
  predatorType: {
    name: "",
    pickedDiscipline: "",
    pickedSpecialties: [],
    pickedMeritsAndFlaws: [],
  },
  ambition: "",
  sect: "",
  generation: 13,
  desire: "",
  touchstones: [],
  attributes: {
    strength: 0,
    charisma: 0,
    intelligence: 0,
    dexterity: 0,
    manipulation: 0,
    wits: 0,
    stamina: 0,
    composure: 0,
    resolve: 0,
  },
  skills: {
    athletics: 0,
    brawl: 0,
    craft: 0,
    drive: 0,
    firearms: 0,
    melee: 0,
    larceny: 0,
    stealth: 0,
    survival: 0,
    "animal ken": 0,
    etiquette: 0,
    insight: 0,
    intimidation: 0,
    leadership: 0,
    performance: 0,
    persuasion: 0,
    streetwise: 0,
    subterfuge: 0,
    academics: 0,
    awareness: 0,
    finance: 0,
    investigation: 0,
    medicine: 0,
    occult: 0,
    politics: 0,
    science: 0,
    technology: 0,
  },
  skillSpecialties: [],
  disciplines: [],
  bloodPotency: 0,
  willpower: {
    totalDots: 0,
    damage: [],
  },
  humanity: 0,
  haven: {
    name: "",
    rating: 0,
    merits: [],
    flaws: [],
  },
  health: {
    totalDots: 0,
    damage: [],
  },
  hunger: 0,
  clanBane: "",
  clanCompulsion: "",
  bloodSurge: "",
  baneSeverity: "",
  birthday: "",
  age: 0,
  embraced: "",
  apparentAge: 0,
  notes: "",
  concept: "",
  experience: {
    total: 0,
    spent: 0,
  },
  history: "",
  merits: [],
  flaws: [],
};
