import type { CharacterSheet } from "./types";

export const EMPTY_CHARACTER: CharacterSheet = {
  name: "",
  chronicle: "",
  description: "",
  player: "",
  sire: "",
  clan: "",
  predatorType: {
    name: "",
    pickedDiscipline: "",
    pickedSpecialties: [],
    pickedMeritsAndFlaws: [],
  },
  ambition: "",
  sect: "",
  generation: 13,
  desire: "",
  touchstones: [],
  attributes: {
    strength: 0,
    charisma: 0,
    intelligence: 0,
    dexterity: 0,
    manipulation: 0,
    wits: 0,
    stamina: 0,
    composure: 0,
    resolve: 0,
  },
  skills: {
    athletics: { dots: 0, specialty: "" },
    brawl: { dots: 0, specialty: "" },
    craft: { dots: 0, specialty: "" },
    drive: { dots: 0, specialty: "" },
    firearms: { dots: 0, specialty: "" },
    melee: { dots: 0, specialty: "" },
    larceny: { dots: 0, specialty: "" },
    stealth: { dots: 0, specialty: "" },
    survival: { dots: 0, specialty: "" },
    "animal ken": { dots: 0, specialty: "" },
    etiquette: { dots: 0, specialty: "" },
    insight: { dots: 0, specialty: "" },
    intimidation: { dots: 0, specialty: "" },
    leadership: { dots: 0, specialty: "" },
    performance: { dots: 0, specialty: "" },
    persuasion: { dots: 0, specialty: "" },
    streetwise: { dots: 0, specialty: "" },
    subterfuge: { dots: 0, specialty: "" },
    academics: { dots: 0, specialty: "" },
    awareness: { dots: 0, specialty: "" },
    finance: { dots: 0, specialty: "" },
    investigation: { dots: 0, specialty: "" },
    medicine: { dots: 0, specialty: "" },
    occult: { dots: 0, specialty: "" },
    politics: { dots: 0, specialty: "" },
    science: { dots: 0, specialty: "" },
    technology: { dots: 0, specialty: "" },
  },
  skillSpecialties: [],
  disciplines: [],
  bloodPotency: 0,
  willpower: {
    totalDots: 0,
    damage: [],
  },
  humanity: 0,
  haven: {
    name: "",
    rating: 0,
    merits: [],
    flaws: [],
  },
  health: {
    totalDots: 0,
    damage: [],
  },
  hunger: 0,
  clanBane: "",
  clanCompulsion: "",
  bloodSurge: "",
  baneSeverity: "",
  birthday: "",
  age: 0,
  embraced: "",
  apparentAge: 0,
  notes: "",
  concept: "",
  experience: {
    total: 0,
    spent: 0,
  },
  history: "",
  merits: [],
  flaws: [],
};
